[package]

name = "carboxyl_window"
version = "0.0.1"
authors = ["Eduard Bopp <eduard.bopp@aepsil0n.de>"]
description = "Functional reactive window API"
homepage = "https://github.com/aepsil0n/carboxyl_window"
repository = "https://github.com/aepsil0n/carboxyl_window"
readme = "README.md"
keywords = ["frp", "reactive", "event", "window"]
license = "LGPL-3.0+"

[dependencies]
carboxyl = "*"
glutin = "*"
image = "*"
pistoncore-input = "*"
piston2d-graphics = "*"
clock_ticks = "*"

[dependencies.glium]
default-features = false

[dependencies.pistoncore-glutin_window]
git = "https://github.com/PistonDevelopers/glutin_window"

[dependencies.glium_graphics]
git = "https://github.com/PistonDevelopers/glium_graphics"
