[package]

name = "carboxyl_window"
version = "0.0.1"
authors = ["Eduard Bopp <eduard.bopp@aepsil0n.de>"]
description = "Functional reactive window API"
homepage = "https://github.com/aepsil0n/carboxyl_window"
repository = "https://github.com/aepsil0n/carboxyl_window"
readme = "README.md"
keywords = ["frp", "reactive", "event", "window"]
license = "LGPL-3.0+"

[dependencies]
carboxyl = "*"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"

[dependencies.glium]
git = "https://github.com/tomaka/glium"
default-features = false

[dependencies.clock_ticks]
git = "https://github.com/tomaka/clock_ticks"
