[package]

name = "frp-bindings"
version = "0.0.1"
authors = ["Eduard Bopp <eduard.bopp@aepsil0n.de>"]

[dependencies]
carboxyl = "*"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"

[dependencies.glium]
git = "https://github.com/tomaka/glium"
features = []
default-features = false

[dependencies.clock_ticks]
git = "https://github.com/tomaka/clock_ticks"

[dependencies.pistoncore-input]
git = "https://github.com/PistonDevelopers/input"
